# Generated by Django 5.1.6 on 2025-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositos',
            name='estado',
            field=models.CharField(choices=[('en_seguimiento', 'En Seguimiento'), ('cerrado', 'Cerrado'), ('inactivo', 'Inactivo')], default='en_seguimiento', max_length=20, verbose_name='Estado del Propósito'),
        ),
    ]
