# Generated by Django 5.1.6 on 2025-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_propositos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinicas',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Modificación'),
        ),
    ]
