# Generated by Django 5.1.6 on 2025-07-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_historiasclinicas_fecha_ultima_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinicas',
            name='motivo_archivado',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Archivado'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado de la Historia'),
        ),
    ]
