# Generated by Django 5.1.6 on 2025-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_historiasclinicas_motivo_archivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinicas',
            name='estado_previo_archivado',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], max_length=20, null=True, verbose_name='Estado Previo al Archivado'),
        ),
    ]
