# Generated by Django 5.1.6 on 2025-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_historiasclinicas_estado_previo_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciongenetica',
            name='diagnostico_final',
            field=models.TextField(blank=True, help_text='El diagnóstico definitivo o las conclusiones finales de la evaluación.', null=True, verbose_name='Diagnóstico Final y Conclusiones'),
        ),
    ]
